# Generated by Django 4.2.4 on 2023-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
